/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.gestao.imagem.view.tela_principal;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author bruno
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lbUsuario = new javax.swing.JLabel();
        btnNotificacao = new javax.swing.JButton();
        lblNomeUsuario = new javax.swing.JLabel();
        mnBar = new javax.swing.JMenuBar();
        mnImagem = new javax.swing.JMenu();
        itmExibirImagens = new javax.swing.JMenuItem();
        mnUsuario = new javax.swing.JMenu();
        itmUsuarioCadastro = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        itmSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        lbUsuario.setText("Usuário: ");

        btnNotificacao.setText("0");

        mnImagem.setText("Imagem");

        itmExibirImagens.setText("Exibir Imagens");
        mnImagem.add(itmExibirImagens);

        mnBar.add(mnImagem);

        mnUsuario.setText("Usuario");

        itmUsuarioCadastro.setText("Cadastro");
        mnUsuario.add(itmUsuarioCadastro);

        mnBar.add(mnUsuario);

        mnSair.setText("Sair");

        itmSair.setText("Sair");
        mnSair.add(itmSair);

        mnBar.add(mnSair);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNotificacao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotificacao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbUsuario)
                        .addComponent(lblNomeUsuario)))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnNotificacao() {
        return btnNotificacao;
    }

    public JDesktopPane getDesktop() {
        return desktop;
    }

    public JMenuItem getItmExibirImagens() {
        return itmExibirImagens;
    }

    public JMenuItem getItmUsuarioCadastro() {
        return itmUsuarioCadastro;
    }

    public JMenuBar getMnBar() {
        return mnBar;
    }

    public JMenu getMnImagem() {
        return mnImagem;
    }

    public JMenu getMnUsuario() {
        return mnUsuario;
    }

    public JLabel getLbUsuario() {
        return lbUsuario;
    }

    public JLabel getLblNomeUsuario() {
        return lblNomeUsuario;
    }

    public JMenuItem getItmSair() {
        return itmSair;
    }

    public JMenu getMnSair() {
        return mnSair;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itmExibirImagens;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmUsuarioCadastro;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenu mnImagem;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenu mnUsuario;
    // End of variables declaration//GEN-END:variables
}
